services:
  - type: web
    name: web-ids-dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    
  - type: web
    name: vulnerable-todo-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn todo_app:app
    plan: free
    envVars:
      - key: IDS_URL
        fromService:
          type: web
          name: web-ids-dashboard
          envVarKey: RENDER_EXTERNAL_URL
